fpga/README.md
=> Updated FPGA README.md

fpga/README.md
=> Corrected GCC toolchain instructions

fpga/README.md
Files changed:
* fpga/README.md: Various fix ups to installation steps.
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>
=> Clean up installation steps 1-4.

fpga/README.md
Files changed:
* fpga/README.md: Fix bitstream link and advise on booting
directly from SD card/thumb drive
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>
=> Fix bitstream link.

fpga/README.md
Signed-off-by: Bart Brosens <bart.brosens@sigasi.com>
=> Correcting link to pre-built FPGA bitstreams

README.md
Hi.  I noticed a couple of small bugs in the links to the cv32e40p repo.
=> Update links to cv32e40p repo and docs

doc/hw-tg-meetings/2020-11-18/minutes.md
=> Added November HW TG meeting notes

README.md
=> Corrected link as per Issue #3

fpga/README.md
=> Modified PULP SDK install to use v1 branch

doc/hw-tg-meetings/2020-12-16/minutes.md
=> Added HW TG notes fromm 2020-12-16 call

README.md, ips_list.yml, rtl/pulpissimo/pulpissimo.sv, rtl/pulpissimo/soc_domain.sv, rtl/tb/tb_pulp.sv, sim/tcl_files/config/vsim.tcl
* added parameter to select core_type
* hard_id for cv32e40p is now equal to 0
* added VSIM_CORE_TYPE to select the core_type
* update REAME
to be merged after https://github.com/openhwgroup/pulp_soc/pull/3
=> integration of cv32e40p

generate-scripts
Signed-off-by: Florian Zaruba <florian@openhwgroup.org>
=> generate_scripts: Fix to generate IP database

docs/github.md, docs/index.rst
Signed-off-by: <florian@openhwgroup.org>
=> doc: Add Github notes page

rtl/generic_FLL/fe/model/fll_stub.sv
Signed-off-by: <florian@openhwgroup.org>
=> Bypass the FLL for the Verilator model

docs/github.md
Signed-off-by: <florian@openhwgroup.org>
=> docs: Add Git workflow

.github/workflows/lint.yml, .readthedocs.yaml, docs/.gitignore, docs/Makefile, docs/auto-docs/apb_gpio_reg_defs.md, docs/auto-docs/apb_interrupt_cntrl_reg_defs.md, docs/auto-docs/apb_soc_ctrl_reg_defs.md, docs/auto-docs/apb_timer_unit_reg_defs.md, docs/auto-docs/udma_ctrl_reg_defs.md, docs/auto-docs/udma_i2cm_reg_defs.md, docs/auto-docs/udma_uart_reg_defs.md, docs/requirements.txt
Signed-off-by: <florian@openhwgroup.org>
=> Fix documentation generation

README.md
Files changed:
* README.md: Document the pitfalls of pre-commit checking.
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>
=> Update README about contributing.

README.md
Hi @timsaxe and @gmartin102, this is a "pipecleaner" pull-request to show how we'll be handling pull-requests to core-v-mcu going forward.
Signed-off-by: Mike Thompson <mike@openhwgroup.org>
=> README: minor update of formatting

rtl/includes/pulp_soc_defines.sv, util/ioscript.py
Signed-off-by: Greg Martin <gmartin@quicklogic.com>
How should open issue be indicated resolved with this PR?  --
=> Fix IDCODE and correct ioscript.py for Event Unit address define

util/format-verible
Signed-off-by: Massimiliano Giacometti <max@openhwgroup.org>
=> check whether verible is installed

.github/workflows/aws.yml
Signed-off-by: Massimiliano Giacometti <max@openhwgroup.org>
=> hook for AWS Codebuild

rtl/vendor/patches/pulp_platform_axi/0004-Initial-steps-towards-regressionable-tests-220.patch
Fyi @MikeOpenHWGroup fixes #229. The other PRs need to be rebased of course.
=> Fix vendor check

README.md, emulation/quickstart/README.md
Added Xilinx Vivado information see #274.
=> Add Vivado version info

CONTRIBUTING.md, README.md, emulation/quickstart/README.md
This PR is mostly a check of the CI flow.  I took the opportunity to add content for new Contribtuors.
=> Quicktest: add info for new contributors

docs/doc-src/ip-blocks/apb_adv_timer.rst
=> Fix bullets

docs/doc-src/efpga_subsystem.rst, docs/doc-src/interrupts.rst
Added more intro information.
Also wanted to test the flow again
=> Update to eFPGA subsystem Intro

emulation/quickstart/README.md
=> Fix up the Quick Start Guide
